title: Fer on software
email: fernando@ariasmarques.com

name: Fer on software
url: "http://fernando.ariasmarques.com/"
description: > # this means to ignore newlines until "baseurl:"
  A developer's life. My thoughts and experiences in my life as a software developer.
disqus_shortname: "ferarias"
use_leaflet: 1
ga_domain: "fernando.ariasmarques.com"
ga_id: "UA-909686-4"
blog_more_posts: 5
prettify_theme: "ghink"

# Build settings
markdown: kramdown
pygments: true
paginate: 3
paginate_path: "blog/page/:num"
permalink: /:year/:month/:day/:title.html
timezone: Europe/Madrid
kramdown:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
gems:
    - jekyll-sitemap
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ferarias
github_username:  ferarias

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


